#!/usr/bin/env bash
# Refresh this workspace's runtime layer from the brains under brains/.
#
# Claude Code loads only .claude/ at the folder you open (this root); it never loads a child repo's
# .claude/. So this script (1) COPIES each brain's .claude/{commands,skills,agents,rules} up into this
# root's .claude/ so they are usable as slash commands here, and (2) regenerates .claude/CAPABILITIES.md,
# a brain-selection index of what each brain holds. Run by /start and /sync. Safe to re-run.
#
# The workspace's own commands and settings are never touched. Files copied by a previous refresh are
# cleared first (so deletions in a brain propagate). NOTE: newly copied slash commands appear only after
# Claude Code is restarted.
set -euo pipefail
cd "$(dirname "${BASH_SOURCE[0]}")/.."          # repos root (the folder holding .claude/)

CLAUDE=".claude"
MANIFEST="$CLAUDE/.copied-manifest"
PROVENANCE="$CLAUDE/COPIED-FROM.md"
CAPS="$CLAUDE/CAPABILITIES.md"
KINDS="commands skills agents rules"
PROTECTED_COMMANDS="start.md sync.md save.md promote-to-department.md workspace-help.md register-repo.md"

[ -d brains ] || { echo "refresh-commands: no brains/ yet; run /start first."; exit 0; }

# 1. Clear what a previous refresh copied (leaves workspace-owned files untouched).
if [ -f "$MANIFEST" ]; then
  while IFS= read -r rel; do [ -n "$rel" ] && rm -rf "$CLAUDE/$rel"; done < "$MANIFEST"
fi
: > "$MANIFEST"
{
  echo "# Copied command layer (auto-generated by /sync and /start; do not hand-edit)"
  echo
  echo "Entities copied up from the brains under \`brains/\` so they work as slash commands, agents, and"
  echo "skills here. A copied command assumes ITS brain's folder as its working directory: cd into that"
  echo "brain first, per the mapping below."
  echo
} > "$PROVENANCE"

# 2. Order brains so individual-* are processed first and shared brains last: on a name collision the
#    shared brain wins over an individual experiment of the same name.
ordered=""; shared=""
for d in brains/*/; do
  [ -d "$d" ] || continue
  case "$(basename "$d")" in individual-*) ordered="$ordered $d" ;; *) shared="$shared $d" ;; esac
done
ordered="$ordered $shared"

copied=0
for braindir in $ordered; do
  [ -d "$braindir" ] || continue
  brain="$(basename "$braindir")"
  src="$braindir.claude"
  [ -d "$src" ] || continue
  for kind in $KINDS; do
    [ -d "$src/$kind" ] || continue
    mkdir -p "$CLAUDE/$kind"
    for entry in "$src/$kind"/*; do
      [ -e "$entry" ] || continue
      base="$(basename "$entry")"
      if [ "$kind" = "commands" ]; then
        case " $PROTECTED_COMMANDS " in *" $base "*) continue ;; esac
      fi
      rel="$kind/$base"
      rm -rf "$CLAUDE/$rel"; cp -a "$entry" "$CLAUDE/$rel"
      echo "$rel" >> "$MANIFEST"
      echo "- \`$rel\`  <-  \`brains/$brain/\`  (run from \`brains/$brain/\`)" >> "$PROVENANCE"
      copied=$((copied+1))
    done
  done
done

# 3. Regenerate the brain-selection index: what each brain holds, with a one-line when-to-use.
{
  echo "# Capabilities: which brain holds what (auto-generated by /sync; do not hand-edit)"
  echo
  echo "Use this to route work to the right brain. Regenerated on every sync from each brain's own"
  echo "structure. Default posture: real and shared work in the shared brain, experiments in your own."
  echo
  for braindir in brains/*/; do
    [ -d "$braindir" ] || continue
    brain="$(basename "$braindir")"
    case "$brain" in individual-*) role="individual brain (your scratch and research; fewer guardrails)" ;;
                     *)             role="shared brain (the default working surface; canon others rely on)" ;; esac
    echo "## $brain"
    echo "_${role}_"
    # a when-to-use summary from the brain's own orientation, if present: the whole
    # first prose paragraph (wrapped lines joined), not just its first line.
    for f in "$braindir"README.md "$braindir"CLAUDE.md; do
      if [ -f "$f" ]; then
        line="$(awk '/^[A-Za-z]/ { found=1 } found { if (/^[[:space:]]*$/) exit; printf "%s ", $0 }' "$f" 2>/dev/null | sed 's/[[:space:]]*$//')"
        [ -n "$line" ] && echo "- summary: $line"
        break
      fi
    done
    if [ -d "$braindir"knowledge ]; then
      # join with ", " (paste -sd cycles multi-character delimiter lists, so awk joins)
      ns="$(ls -1 "$braindir"knowledge 2>/dev/null | grep -v '^_' | awk 'NR > 1 { printf ", " } { printf "%s", $0 } END { print "" }')"
      [ -n "$ns" ] && echo "- knowledge namespaces: $ns"
    fi
    for area in tools workflows departments; do
      if [ -d "$braindir$area" ]; then
        c="$(ls -1 "$braindir$area" 2>/dev/null | grep -vi readme | wc -l | tr -d ' ')" || true
        [ "$c" != 0 ] && echo "- $area: $c" || true
      fi
    done
    for etype in commands agents skills; do
      d="$braindir.claude/$etype"
      if [ -d "$d" ]; then
        c="$(ls -1 "$d" 2>/dev/null | wc -l | tr -d ' ')" || true
        [ "$c" != 0 ] && echo "- $etype: $c (copied up; usable here after a restart)" || true
      fi
    done
    echo
  done
} > "$CAPS"

echo "refresh-commands: copied $copied entities and rebuilt $CAPS. Restart Claude Code to load new slash commands."
